README.md
In my next.js environment, after I created a page in `pages/foo/bar.tsx`, the page was only accessible through url `/foo/bar.html`.
I was able to access it through `/foo/bar` after adding `"cleanUrls": true` to my `firebase.json` hosting config.
my `next.config.js`:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
reactStrictMode: true,
}
module.exports = nextConfig
```
my `package.json`:
```json
{
"engines": {
"node": "16"
},
"scripts": {
"dev": "firebase emulators:start",
"postinstall": "firebase --open-sesame frameworkawareness"
},
"dependencies": {
"firebase": "^9.8.1",
"firebase-admin": "^10.0.2",
"firebase-functions": "^3.21.2",
"firebase-tools": "^10.9.2",
"next": "12.1.6"
},
"devDependencies": {
"@types/react": "18.0.9",
"@types/react-dom": "18.0.4", …
```
=> Add common configurations to README.md

.github/workflows/test.yml, package-lock.json, package.json, src/next.js/index.ts
Next.js' minimal mode is unstable, I was using it to opt-out of ISR and touching the filesystem in Cloud Functions but it seems it also disables Image Optimzation—so drop it. There is no benefit to us ATM as it seems to be for edge compute rather than serverless.
* Drop minimal mode
* Bump version
* Fix firebase-tools devDep for test suite
This is purely contained within the firebase-frameworks NPM dep, no firebase-tools patch is required to take advantage.
=> Drop Next minimal mode, fixes image optimization

src/next.js/index.ts
Is there a way to do this that doesn't necessitate our spinning up multiple next instances?
=> Add hostname and port to next custom server

src/index.ts, src/utils.ts
Apart from `process.env.__FIREBASE_DEFAULTS__`, check whether the Firebase JS SDK can be imported to assume that the app is using it. In some cases the env. variable was set even if the app was not using the Firebase JS SDK.
Fixes https://github.com/firebase/firebase-tools/issues/5996
=> Fix `usingFirebaseJsSdk`

.eslintignore, .eslintrc.cjs, .github/workflows/test.yml, .prettierignore, .prettierrc.cjs, src/utils.ts
We have the following broken E2E tests in our matrix:
- `next`
- `nuxt`
- `nuxt3`
I deactivated them, for now, but plan to fix (at least) `next` in the near future.
The `contrib` action should not run e2e test, but rather local-build the package (and run unit tests should we add any later).
=> Fix GitHub action

package.json
This change makes `create-next-app` non-interactive by skipping the question `Would you like to use ESLint with this project?`
=> add `--eslint` to create-next-app

package-lock.json, package.json
fixes https://github.com/firebase/firebase-tools/issues/6109
**Question:** After we cut a new release, I thought we might need to bump the [`FIREBASE_FRAMEWORKS_VERSION` constant](https://github.com/firebase/firebase-tools/blob/v12.4.3/src/frameworks/constants.ts#L28) in `firebase-tools`, but since it has the `^`, it should download the new `firebase-frameworks` version right?
=> allow firebase sdk v10 in peer deps

packages/@apphosting/adapter-nextjs/src/bin/build.ts
=> Update adaptor build script

packages/@apphosting/adapter-nextjs/src/bin/build.ts
* For standalone and no CDN static directory should be placed in .next ([see docs here](https://nextjs.org/docs/pages/api-reference/next-config-js/output#automatically-copying-traced-files))
* Public dir existence check was looking at the wrong spot
* Use relative directories in the bundle.yaml
* Fix the race conditions in the folder moving which were wiping files out
=> Apphosting dir fixes

packages/firebase-frameworks/package.json
v0.11.2 was not released in Github Actions due to the package.json version being out of date, i need to make this failure more obvious. Will allow https://github.com/firebase/firebase-tools/issues/6688 to be fixed
=> Bump ff version

.eslintrc.cjs, package-lock.json, package.json, packages/@apphosting/adapter-angular/src/bin/build.ts, packages/@apphosting/adapter-angular/src/interface.ts, packages/@apphosting/adapter-angular/src/utils.ts
angular build adapter script 
output directory structure & bundle.yaml file after running adapter:
=> angular build adatper draft

package-lock.json, packages/@apphosting/adapter-angular/package.json, packages/@apphosting/adapter-angular/src/bin/build.ts, packages/@apphosting/adapter-angular/src/utils.ts
Currently, the Angular adapter is unable to specify a custom build command to run the Angular application builder. It also makes certain assumptions that no longer hold true in monorepo contexts. We adjust those conditions to enable builds of Angular projects using monorepo tooling.
=> Support monorepo builds in Angular adapter

.github/workflows/test.yml, scripts/publish.js
Changes the deploy flow to use wombot publishing
=> add wombot support

packages/@apphosting/adapter-angular/src/utils.ts
Check one layer up in require.resolve
=> Fix pnpm build for angular

.github/workflows/test.yml, package-lock.json, packages/@apphosting/create/package.json, packages/@apphosting/create/src/bin/create.ts, packages/create-next-on-firebase/package.json, packages/create-next-on-firebase/src/bin/create.ts, starters/angular/basic/README.md, starters/angular/basic/package-lock.json, starters/angular/basic/package.json, starters/nextjs/basic/README.md
* Add package-mananger choices to the NPX `@apphosting/create` script, if `npm|yarn|pnpm init|create @apphosting` is used don't prompt—use the package manager from the command
* Allow for interactive directory picking
* Wire up create-next-on-firebase so `npm init next-on-firebase` works appropriately
* Download the starters based off the chosen framework
* Add `@types/express` to the Angular starter
* READMEs for the starters
* Drop Node 16 from the tests as we're having engine issues & no longer support v16
=> Use starters for App Hosting init

packages/firebase-frameworks/src/sveltekit/index.ts
Fix SvelteKit server responses. Huge thanks to @m3tasploit for the initiative. This PR differs from #159 by always responding with a Buffer.
Created test deployments here:
- With this fix: https://fb-tools-dev--svelkite-buffer-test-9b25lhcv.web.app/
- With the current production server: https://fb-tools-dev--svelkite-buffer-test-prod-6sdoxhqh.web.app/
Click in the `request` buttons to test requests. Note that images are broken with the current production server.
=> fix SvelteKit server responses

package-lock.json, packages/@apphosting/adapter-angular/package.json, packages/@apphosting/adapter-nextjs/package.json
The only thing that's changing in the Angular adapter's package.json is the @apphosting/common dependency - there's just some weirdness going on with the formatter that's setting it back to 2 space from 4.
=> Update @apphosting/common dependency in adapters

scripts/github.js
https://github.com/FirebaseExtended/firebase-framework-tools/pull/220 includes dependencies for PRs, but not for releases. We were subtly filtering out all packages from the build except for the package targeted for releases, resulting in failed pre-release builds for the framework adapters that now depend on @apphosting/common.
=> Include dependencies and dependents when scoping build command for releases

starters/angular/basic/server.ts
From https://firebase.google.com/docs/app-hosting/get-started
We found the Cloud Run service is failing with the following error message:
> The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable
Because it doesn't have the LOCA=true variable
Removing this, fix the issue, not sure if you want to accept this PR, or if you would like to inject the `LOCAL=true` variable on the deployment process.
=> Remove LOCAL flag to fix deployment on Cloud Run

packages/firebase-frameworks/src/express/index.ts
- Use the `incomingMessageFromExpress` function in the express request handler (used by Astro handler) in order to create a Node.js HTTP server’s incoming message object from an Express Request object.
- Fixes [#7446](https://github.com/firebase/firebase-tools/issues/7446) and [#7046](https://github.com/firebase/firebase-tools/issues/7046) where multipart/form-data stream was exhausted before making it to the application api endpoint causing an error when trying to read the stream again.
=> Use incomingMessageFromExpress function in express request handler

packages/firebase-frameworks/package.json
The current sharp peer dependency is out of date. If you're trying to deploy a function that would use sharp, the deploy errors because there's a version mismatch. This is because SEMVER < 1 counts minor releases (0.xx) as potentially breaking, so `0.32` won't resolve with `0.33.x` installed
=> Update sharp version

scripts/github.js
Fixes an error on the ci process when running the build script that prevents the firebase-frameworks release to be published.
=> Add single quotes to --scope arg value in lerna list command

package-lock.json, packages/@apphosting/adapter-angular/package.json, packages/@apphosting/common/package.json, packages/@apphosting/common/src/index.ts
This interface will be used in the other adapters as the output bundle
=> Add output bundle spec to common module

package-lock.json, package.json, packages/@apphosting/adapter-angular/package.json, packages/@apphosting/adapter-nextjs/package.json, packages/@apphosting/build/package.json, packages/@apphosting/discover/package.json, scripts/build.js, scripts/github.js, scripts/publish.js, scripts/test.js
Seeing failures [since the changes to `@apphosting/common`](https://github.com/FirebaseExtended/firebase-framework-tools/actions/runs/10822830253/job/30027361965?pr=232). It turns out that in lerna, for the dependency graph to pick up dependents / dependencies the version in the package.json dependencies needs to be in the form of `*`
* Change monorepo dependencies to `*`, that's the easy part
* Now we don't want to allow any version of `@apphosting/common` as a dependency of `@apphosting/adapter-*`, so let's pin before we publish to the registry
* Do two passes on the scopedLernaList (fka filteredLernaList)
1. make a new package.json—set the new version and publishConfig
1. pin dependencies to any versions from the first pass, write to disk, publish
* Topo sort the lerna list, so …
=> Fix apphosting/common in build/publish

packages/@apphosting/adapter-angular/src/bin/build.ts, packages/@apphosting/adapter-angular/src/utils.ts
This pr will add additional builders allowed and skip generating the output bundle if it already exists
=> Add support for angular meta framework

packages/@apphosting/adapter-angular/src/interface.ts
Add additional support for prerendered object routes
=> fix angular19

README.md
- Remove second `adapterVersion` and replace it with `frameworkVersion`.
- Remove `Npm` from metadata field name
- Make `runCommand` a string instead of a list
=> Fix typo in example bundle.yaml

package-lock.json, packages/firebase-frameworks/package.json
Update peerDependencies so downstream dependencies have the option of using firebase-admin 13.x
Duplication/Resolves https://github.com/FirebaseExtended/firebase-framework-tools/pull/288
=> Allow firebase-admin 13.x

package-lock.json, packages/@apphosting/adapter-nextjs/package.json, packages/@apphosting/adapter-nextjs/src/utils.ts
Seeing the following error when building a nextjs app in staging:
The error was introduced in the 14.0.10 release of the NextJs adapter, with the header override changes.
=> NextJS Adapter Bug Fix - Invalid next import

package-lock.json, packages/@apphosting/adapter-angular/package.json, packages/@apphosting/adapter-angular/src/utils.ts
This should fix the bug where people were occasionally the manifest file would add new line characters, breaking the parsing https://github.com/FirebaseExtended/firebase-framework-tools/issues/307
=> Make Angular manifest parsing more robust

README.md, packages/@apphosting/adapter-nextjs/src/overrides.ts, packages/@apphosting/adapter-nextjs/src/utils.ts, packages/@apphosting/common/src/index.ts
Update the interface and the readme
=> Update outputBundleConfig to include outputfiles

starters/angular/basic/package-lock.json, starters/angular/basic/package.json
The [basic Angular starter](https://github.com/FirebaseExtended/firebase-framework-tools/tree/main/starters/angular/basic) is failing to build in App Hosting with this error:
```
Error: Cannot find module '@angular-devkit/core/node'
```
This is an issue with the Angular adapter, but while a fix is in the works for that, this PR directly adds `@angular-devkit/core` as a dev dependency to the starter template to unblock deploys.
=> Fix deploy for basic Angular starter

starters/nextjs/firebase-ecommerce/.gitignore, starters/nextjs/firebase-ecommerce/README.md, starters/nextjs/firebase-ecommerce/apphosting.yaml, starters/nextjs/firebase-ecommerce/dataconnect-generated/js/default-connector/README.md, starters/nextjs/firebase-ecommerce/dataconnect-generated/js/default-connector/esm/index.esm.js, starters/nextjs/firebase-ecommerce/dataconnect-generated/js/default-connector/index.cjs.js, starters/nextjs/firebase-ecommerce/dataconnect-generated/js/default-connector/index.d.ts, starters/nextjs/firebase-ecommerce/dataconnect/.dataconnect/schema/main/input.gql, starters/nextjs/firebase-ecommerce/dataconnect/.dataconnect/schema/prelude.gql, starters/nextjs/firebase-ecommerce/firebase.json
1. Removes all references to a particular project
2. Adds generated files and project-specific files to .gitignore
3. Updates apphosting.yaml to include instructions where to find values
4. Update getting started, including references to using the app hosting emulator
NOTE: It seems like there are changes made to dataconnect generated files even when adding generated files to .gitignore; I'm not entirely sure how to drop them.
=> Update getting started experience

package-lock.json, packages/@apphosting/adapter-nextjs/package.json, packages/@apphosting/adapter-nextjs/src/bin/build.spec.ts, packages/@apphosting/adapter-nextjs/src/utils.ts
Filters out all directories other than .next/standalone, in practice this will pretty much only delete the extra node_modules in the root directory, improving build speeds
=> Filter out node_modules

package-lock.json, packages/@apphosting/adapter-nextjs/package.json, packages/@apphosting/adapter-nextjs/src/bin/build.spec.ts, packages/@apphosting/adapter-nextjs/src/utils.ts
Reverts FirebaseExtended/firebase-framework-tools#346
Temporarily reverts this change as it breaks NextJS Monorepo setups. See https://github.com/FirebaseExtended/firebase-framework-tools/issues/349.
=> Revert "Filter out node_modules"

packages/@apphosting/adapter-nextjs/src/bin/build.spec.ts, packages/@apphosting/adapter-nextjs/src/utils.ts
This is part one of making our adapter builds idempotent.
=> Copy resources into output directory instead of moving them.

packages/@apphosting/adapter-nextjs/package.json, packages/@apphosting/adapter-nextjs/src/bin/build.spec.ts, packages/@apphosting/adapter-nextjs/src/utils.ts
part of making build adapters idempotent
=> gitignore .apphosting/

packages/@apphosting/adapter-angular/package.json, packages/@apphosting/adapter-angular/src/utils.ts, packages/@apphosting/common/package.json
This addresses an issue where Turbo builds, when used with Angular, introduce extraneous "web:build:" prefixes into the raw JSON manifest output. This PR strips these undesired prefixes, ensuring the Angular manifest get extracted in a proper format.  
This PR also bumps the angular adapter and the common folder versions. With the angular manifest parsing fix and the monorepo args split fix, the angular + turbo will be fixed.
=> Refine and clean the Turbo + Angular JSON manifest output

packages/@apphosting/adapter-angular/src/interface.ts, packages/@apphosting/common/src/index.ts
- Add interfaces for the apphosting config, while sharing what can be shared with the bundle config
- remove unused and duplicate interfaces in adapter-angular
- Add 'Build' enum value for envvars availability. This was previously limited to "Runtime" because it was used only for bundle.yaml's envvars which are envvars set by the adapter after a build to be used for runtime. Now the envvars interface will be shared with the apphosting config
=> Add apphosting config interface to common.
